language: node_js
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
dist: trusty
install:
  - npm install
node_js:
  - "8"
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS newcommerce_test;'
  - mysql -e "use mysql; update user set authentication_string=PASSWORD('123') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - service mysql restart
  - cp .env.example .env
  - cp config/database.json.example config/database.json

before_script:
  - npm run pretest
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
  - "chmod +x ./cc-test-reporter"
  - "./cc-test-reporter before-build"
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
