const OffersRel = {
  tableName: 'sp_oferta_relacionado_sel as OffersRel',
  id: 'ID_OFERTA',
  fields: [
    'ID_OFERTA as idOffer',
    'REFERENCIA_OFERTA as refOffer',
    'REFERENCIA_PRODUTO as refProduct',
    'ID_PROJETO as idProject',
    'PROJETO as project',
    'NOME as name',
    'URL_SLUG as slug',
    'ID_FAMILIA as idFamily',
    'ID_GRUPO as idGroup',
    'ID_SUBGRUPO as idSubGroup1',
    'ID_SUBGRUPO02 as idSubGroup2',
    'ID_SUBGRUPO03 as idSubGroup3',
    'FAMILIA as familyName',
    'GRUPO as groupName',
    'SUBGRUPO as subGroupName1',
    'SUBGRUPO02 as subGroupName2',
    'SUBGRUPO03 as subGroupName3',
    'URL_AFILIADO as urlAffiliate',
    'URL_WEBSITE as urlWebsite',
    'URL_DESTINO as urlDestiny',
    'URL_IMAGEM as urlImage',
    'REGULAR_PRICE_REAL as regularPriceReal',
    'SALE_PRICE_REAL as salePriceReal',
    'REGULAR_PRICE_DOLAR as regularPriceDolar',
    'SALE_PRICE_DOLAR as salePriceDolar',
    'FLAG_INDISPONIVEL as flagUnavaliable',
    'FLAG_NAOBRASIL as flatNotBrazil',
    'FLAG_FREESHIPPING as freeShipping',
    'PS_REGISTROS_COUNT as count',
  ],
  args: [
    'idOffer',
    'limit',
    'page',
    'idColumn',
    'direction',
  ],
};

export default OffersRel;
