const Search = {
  tableName: 'spOfertaBuscaHorizontalSel as Search',
  id: 'idOffer',
  fields: [
    'idOferta as idOffer',
    'referenciaOferta as refOffer',
    'referenciaProduto as refProduct',
    'idProjeto as idProject',
    'projeto as project',
    'nome as name',
    'urlSlug as slug',
    'idFamilia as idFamily',
    'idGrupo as idGroup',
    'idSubgrupo as idSubGroup1',
    'idSubgrupo02 as idSubGroup2',
    'idSubgrupo03 as idSubGroup3',
    'familia as familyName',
    'grupo as groupName',
    'subgrupo as subGroupName1',
    'subgrupo02 as subGroupName2',
    'subgrupo03 as subGroupName3',
    'urlAfiliado as urlAffiliate',
    'urlWebsite as urlWebsite',
    'urlDestino as urlDestiny',
    'urlImagem as urlImage',
    'regularPriceReal as regularPriceReal',
    'salePriceReal as salePriceReal',
    'regularPriceDolar as regularPriceDolar',
    'salePriceDolar as salePriceDolar',
    'flagIndisponivel as flagUnavaliable',
    'flagNaoBrasil as flatNotBrazil',
    'flagFreeshipping as freeShipping',
    'RregistrosCount as count',
  ],
  args: [
    'idProject',
    'word1',
    'word2',
    'word3',
    'word4',
    'word5',
    'word6',
    'word7',
    'word8',
    'word9',
    'word10',
    'limit',
    'page',
    'idColumn',
    'direction',
  ],
};

export default Search;
