const Offers = {
  tableName: 'TBL_OFERTAS as Offers',
  id: 'idOffer',
  fields: [
    'ID_OFERTA as idOffer',
    'REFERENCIA_OFERTA as refOffer',
    'REFERENCIA_PRODUTO as refProduct',
    'ID_PRODUTO_PRINCIPAL as idProductMain',
    'ID_MERCHANT as idMerchant',
    'ID_PROJETO as idProject',
    'ID_FAMILIA as idFamily',
    'ID_GRUPO as idGroup',
    'ID_SUBGRUPO as idSubGroup1',
    'ID_SUBGRUPO02 as idSubGroup2',
    'ID_SUBGRUPO03 as idSubGroup3',
    'PROJETO as project',
    'NOME as name',
    'FAMILIA as familyName',
    'GRUPO as groupName',
    'SUBGRUPO as subGroupName1',
    'SUBGRUPO02 as subGroupName2',
    'SUBGRUPO03 as subGroupName3',
    'URL_SLUG as slug',
    'URL_AFILIADO as urlAffiliate',
    'URL_DESTINO as urlDestiny',
    'URL_IMAGEM as urlImage',
    'REGULAR_PRICE_REAL as regularPriceReal',
    'SALE_PRICE_REAL as salePriceReal',
    'REGULAR_PRICE_DOLAR as regularPriceDolar',
    'SALE_PRICE_DOLAR as salePriceDolar',
    'META_TITLE as metaTitle',
    'META_DESCRIPTION as metaDescription',
    'META_FOCUSKWD as metaFocusKeyword',
    'OFERTA_CARTA_VENDA as offerSalesLetter',
    'FLAG_INDISPONIVEL as flagUnavaliable',
    'FLAG_DESTINO404 as flagDestiny',
    'FLAG_NAOBRASIL as flatNotBrazil',
    'FLAG_FREESHIPPING as freeShipping',
    'flag_noindex as noindex',
  ],
};

export default Offers;
